### ISSUE TITLE
Make sure the UI can fill the screen

### ISSUE THREAD

**Issue by thatch** [bartei/rotary-controller-python#9]
With non-X SDL on an HDMI 1024x600 display, the top ~15% is unused.  I suspect this is trivial but could use some hints for kivy.

![image](https://github.com/bartei/rotary-controller-python/assets/49834/0751d3c3-ee8b-4234-ac42-b249a13d79b2)

**Comment by thatch** [comment]
This display appears to not like the default (800, 600) window size, and the console framebuffer that I saw was stretched to fit the screen was (640, 480).  Here's the minimal change I could sort out to do that in kivy:

```diff
diff --git a/rotary_controller_python/main.py b/rotary_controller_python/main.py
index b6f506f..ad7a9d8 100644
--- a/rotary_controller_python/main.py
+++ b/rotary_controller_python/main.py
@@ -3,6 +3,7 @@ from loguru import logger as log
 
 from kivy.app import App
 from kivy.clock import Clock
+from kivy.core.window import Window
 from kivy.properties import (
     StringProperty,
     NumericProperty,
@@ -139,6 +140,7 @@ class MainApp(App):
         self.home = Home(device=self.device)
         self.task_update = Clock.schedule_interval(self.update, 1.0 / 30)
         Clock.schedule_interval(self.blinker, 1.0 / 4)
+        Window.size = (640, 480)
         return self.home
```

**Comment by bartei** [comment]
@thatch My current layout configuration has fixed height for the dro display rows, that's why when you use a display with a different aspect ratio compared to the officila rpi display you get black empty spaces. I will prepare a branch with dynamic row height sizes so we can test it. I wanted the buttons to be square and reasonably sized, that's why they have a fixed dimension right now. Dealing with different aspect ratios is always difficult!

**Comment by bartei** [comment]
I can add a filler at the bottom of the side toolbar to handle the variation in the display dimensions, probably could do the same for the dro rows, just add a dynamic filler block with a gray background between the axis control and the dro position rows

**Comment by thatch** [comment]
Yeah, this is a lot better.  Thanks!
